PreCommit:
  AuthorName:
    enabled: false
  EsLint:
    enabled: true
    # https://github.com/sds/overcommit/issues/338
    required_executable: "yarn"
    command: ["yarn", "eslint"]
    flags: []
  HamlLint:
    enabled: true
  MergeConflicts:
    enabled: true
    exclude:
      - "**/conflict/file_spec.rb"
      - "**/git/conflict/parser_spec.rb"
  # prettier? https://github.com/sds/overcommit/issues/614 https://github.com/sds/overcommit/issues/390#issuecomment-495703284
  RuboCop:
    enabled: true
  #    on_warn: fail # Treat all warnings as failures
  ScssLint:
    enabled: true
  MarkdownLint:
    enabled: true
    description: "Lint documentation for Markdown errors"
    required_executable: "node_modules/.bin/markdownlint"
    flags: ["--config", ".markdownlint.yml", "doc/**/*.md"]
    install_command: "yarn install"
    include:
      - "doc/**/*.md"
  Vale:
    enabled: true
    description: "Lint documentation for grammatical and formatting errors"
    required_executable: "vale"
    flags: ["--config", ".vale.ini", "--minAlertLevel", "error", "doc"]
    install_command: "brew install vale # (or use another package manager)"
    include:
      - "doc/**/*.md"

CommitMsg:
  TextWidth:
    enabled: true
    min_subject_width: 8 # three 2-letter words with 2 spaces
    max_subject_width: 72
    quiet: false

  EmptyMessage:
    enabled: true
    required: true
    description: "Checking for empty commit message"
